### PR TITLE
Graph Viewer

### PR DESCRIPTION
**Pull request by kjmahalingam**
This PR updates the graph viewer and exporter, and incorporates `shr-graph-export` into the toolchain.

In order to test this functionality, first set `implementationGuide.includeGraph` in your desired IG config file to `true`. Then, run the toolchain, followed by the IG publisher using this config file, as you usually would.

After doing this, open the IG, and you should see a `Graph Viewer` tab on the menu bar. Click on this, and confirm that the graph viewer is working as expected. You can select a desired entry in the list on the left of the frame, and then the graph will be shown for that entry.

Check that:

- All graphs display without causing an error
- Nodes can be hovered over to display an overlay (primitives other than some concepts will not have an overlay
- The center node of each graph can be clicked on to display its corresponding entry in the IG

### CODE REVIEW

**Comment by mint-thompson** [comment]
Encountered a few issues while testing this out. All of these tests were performed on a Windows machine. Some of these are probably safe to defer in the interest of making the graph viewer available.
- In IE, the graph did not display at all due to a javascript error: `SCRIPT5: Access is denied. respond.min.js (70,15)`.
- In Chrome and Firefox, at default zoom levels, the overlay for elements near the right edge of the graph would extend past the visible area, making them only partially readable. This can be worked around by middle-clicking and moving the mouse right to scroll the graph (in both Firefox and Chrome) or by pressing the right arrow key (Chrome only). Edge also displayed this issue when zoomed in (tested at 150%), but not at default zoom. In the cases of Firefox and Chrome, zooming out would not work around this.
- In Firefox, clicking on the center node of the graph caused an error: `NS_ERROR_DOM_PROP_ACCESS_DENIED: Access to property denied` on `sketch.js:191`.
- In Chrome and Edge, clicking on the center node of the graph caused the IG entry to appear inside the `graph` iframe, leading to unusual display states.
image

- In Chrome, Edge, and Firefox, the `jsmind-inner` div is slightly taller than its containing frame due to the border, which causes a vertical scrollbar to appear in the graphFrame. The page's contents are also slightly taller than the window, which causes a vertical scrollbar to appear at the window level.

Now, for a few minor notes from the code:
- I am glad to see that the title field is useful here.
- For the selection menu: is it realistic to try to generate this during publication rather than on page load? Or, is this something that may need to change after publication? Either way, it seems to be working correctly, so I feel like it's not a big deal.

**Comment by cmoesel** [comment]
Great review, @mint-thompson.  Thank you for the in-depth analysis and testing.  I will hold off reviewing until @kjmahalingam has had a chance to address your findings.

**Comment by jafeltra** [comment]
This is probably out of scope for this PR, but do you think it would be useful to add any lint or tests to this exporter? It seems like there are other exporters that support a combination of lint and/or tests.

**Comment by kjmahalingam** [comment]
@mint-thompson Thanks for the awesome feedback. I'm fixing these issues now.

@jafeltra You're right that that's a good idea. I think at this point, yes, I would prefer to defer that to a future task, but we should definitely have those.

**Comment by kjmahalingam** [comment]
The above errors have been addressed. All have been fixed except for the first one:

"In IE, the graph did not display at all due to a javascript error: _SCRIPT5: Access is denied. respond.min.js (70,15)._"

This error is, surprisingly, out of scope of this PR. This displays because the `fhir.css` file causes errors in **all** browsers, since it cannot be accessed on **any** page of the IG. It was a pre-existing error. For example, in Chrome, here is how the error displays:

_Access to XMLHttpRequest at 'file:///Users/kmahalingam/shr-tools/packages/shr-cli/out/fhir/guide/output/fhir.css' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https. repond.min.js:6_

It turns out that the graph on IE is the first page to have noticeable effect from this error, despite the fact that it's existed for a while in every page. Presumably, IE halts display of the graph because it noticed a script has an error, but all other browsers still proceed even in the presence of an error.

This should be fixed, but it should be fixed in a different ticket.

@cmoesel -- This should be ready for your final review now.

**Comment by kjmahalingam** [comment]
There were a few minor usability issues that were addressed in the latest commit.

- Underline on hover on the center node of each graph, to indicate that it is a link.
- Border around the key to separate it from the zoom buttons.
- Default text when a graph isn't selected, to indicate the user should select one.

**Comment by kjmahalingam** [comment]
**Graph Viewer**

The new Graph Viewer is an interactive graphical visualization of the primary entries in an Implementation Guide. The Graph Viewer is yet another automatic export included into the CIMPL toolchain.

GraphViewer

To generate an IG with the Graph Viewer included, please ensure that the config file supplied to the CLI has an `implementationGuide.includeGraph` field which is set to `true`. Additionally, ensure that there is at least one entry listed as primary for this IG (either through the soon-to-be-deprecated `implementationGuide.primarySelectionStrategy` field in the config file, or through the `contentProfile` field in the config file. Otherwise, there will be no Graph Viewer included in the IG.

Once the IG is published, click on the Graph Viewer tab in the top menu. By clicking on one of the primary entries listed on the left of the graph viewer, a user can view the visual representation of this entry's logical model. Hovering over nodes provides a description if available. Clicking on the root node will take the user to the IG page associated with this entry. Branches can be collapsed or expanded by clicking on the small circles connected to them.

**Review by cmoesel — APPROVED** [review]
This is pretty darn cool!  Thanks!

**Pull request merged**
