### PR TITLE
Update to FHIR 3.0.2 and 4.0.1

### PR DESCRIPTION
**Pull request by cmoesel**
**WHEN MERGING, PLEASE USE SQUASH AND MERGE**

**NOTE: DESCRIPTION UPDATED NOV 25 TO REFLECT RECENT UPDATES**

Updates definition files to 3.0.2 and 4.0.1 and updates logic to reflect new version numbers where necessary.

Also includes a minor fix related to cleaning up extensions that are not used in profiles.

Lastly, updates the FHIR IG Publisher to: ~`FHIR IG Publisher Version 1.0.0-SNAPSHOT - Built 2019-11-19T20:12:38.173+11:00 - Git 0bc883e6329b`~ `FHIR IG Publisher Version 1.0.2-SNAPSHOT - Built 2019-11-21T18:57:28.632+11:00 - Git 16d4b6a0782f`

To test:

* ~I think you should be able to use `shr-spec` `master` or `dev6` branch (I used `dev6`)~
* Use `shr-spec` `fix_bad_vs_urls` branch (which is based on `dev6` w/ two important fixes)

R4:
* `node . --clean -c ig-mcode/ig-mcode-r4-config.json /path/to/shr-spec/spec`
* `yarn ig:publish`
* `yarn ig:qa` -- there will be some expected errors about codesystems.html and unresolvable value sets.  That's ok.
* `yarn ig:open` -- just look around and ensure nothing is obviously wrong

STU3:
* ~set `"includeLogicalModels": false,` in the `shr-spec/spec/ig-all/ig-all-stu3-config.json` file~ _(no longer necessary)_
* `node . --clean -c ig-all/ig-all-stu3-config.json /path/to/shr-spec/spec`
* ~there is a known bug with AllergyIntolerance, so you need to:~
  * ~search for `obf-AllergyIntolerance` in `out/fhir/guide/ig.json` and remove its entry~
  * ~search for `obf-AllergyIntolerance` in `out/fhir/guide/resources/ig.xml` and remove its entry~
  * _the above hacks aren't necessary if you use the `fix_bad_vs_urls` branch_
* `yarn ig:publish` -- then wait a LOOOOONG time.  Go get lunch.  Then wait longer still.
* `yarn ig:qa` -- there will be lots of errors, but these are expected because its trying to use R4 profiles and extensions in STU3.  This is not a new problem.
* `yarn ig:open` -- just look around and ensure nothing is totally wrong

### CODE REVIEW

**Comment by ngfreiter** [comment]
Everything works fine for R4, but when I try to test out STU3 I get the following:
Capture
@mint-thompson I think you originally came across the AllergyIntolerance bug, does this look similar to the error you got from that? As in maybe I am not removing AllergyIntolerance correctly? Otherwise I'm not sure what is going on here, and I don't know if this is an issue on my end or an issue with this PR. If anyone else wants to give the STU3 a run and see if they get errors that would be great.

**Comment by cmoesel** [comment]
@ngfreiter -- here are diffs showing how I deleted the `AllergyIntolerance` entries.

In out/fhir/guide/ig.json:
image

In out/fhir/guide/resources/ig.xml:
image

And you need to set `"includeLogicalModels": false` in the config file.  I just ran this all last night, so it *should* work.

**Comment by jafeltra** [comment]
@cmoesel I tried to use STU3 and followed your instructions and confirmed I deleted the same things your diffs show, and I still get the same error that @ngfreiter mentioned earlier.

**Comment by cmoesel** [comment]
Hrmmmm...

**Comment by cmoesel** [comment]
True confessions... to save time, I was using a txCache from a previous run.  Maybe that made a difference?  Anyway, you can give it a shot.  Try unzipping the attached and putting the `txCache` folder at `out/fhir/guide/txCache`.  Then run the publisher again.

[txCache.zip](https://github.com/standardhealth/shr-tools/files/3870866/txCache.zip)

**Comment by ngfreiter** [comment]
Unfortunately, I still get the same error, even using that cache.

**Comment by cmoesel** [comment]
OK.  I'm reproducing that error now too.  I'll try to dig into it more to see what's going on.

**Comment by cmoesel** [comment]
OK.  I've successfully figured out the problem.  It was bad valueset URLs.  See standardhealth/shr-spec#384 for details.  This also resulted in me submitting a PR against the FHIR IG Publisher to avoid the crash and print a more helpful message (see HL7/fhir-ig-publisher#42).

Now you also don't need to do those crazy hacks to get STU3 to work.  As long as you use the `fix_bad_vs_urls` branch, it just _works_.  I've updated the PR description instructions to indicate the new process.

The only thing I've changed in _this branch_ since I submitted the PR is that I updated the IG Publisher jar again.

**Comment by ngfreiter** [comment]
Ok so my build failed again:
Capture
But this time it seems like it was a Jekyll problem. The ig still built and I was able to click around and everything looked fine, but no qa was generated. Since this worked for you @cmoesel, I would be fine approving this and not holding it up over Jekyll breaking for me. I'd probably feel better if someone else could try the stu3 build though.

**Comment by cmoesel** [comment]
The build infrastructure is very fickle.  It's possible something changed server-side too.  I'll try STU3 again myself.  I can't remember if I build *all* of STU3 yesterday or only one of the smaller STU3 configs...  I *think* I did all STU3, but I'm not 100% positive.

**Comment by cmoesel** [comment]
Just checked.  Looks like for some reason I quit out of stu3 at the very end (I think I had to leave the coffeeshop I was at) -- but I seem to have gotten further than you!
image

BTW -- faster time is because I used a `txCache`.

**Comment by ngfreiter** [comment]
I don't know if this could cause the difference, but I did use `dev6` instead of `fix_bad_vs_urls` since that branch had been merged into `dev6`. But I don't see how that would cause the issue.

**Comment by cmoesel** [comment]
Those branches should be equivalent -- so I doubt it.  I'm running STU3 again now to see what happens.

**Comment by cmoesel** [comment]
The FHIR team made a breaking page to the package format last night, requiring a new IG Publisher jar.  I've just pushed it here since the old jar no longer works.

I ran STU3 again, but it crashed at the end because Java ran out of memory (after an hour).  I think that all-stu3 is just _too big_.  So, I tested against `ig-sw` instead, since it is also STU3:
```
node . -c ig-sw/ig-sw-config.json ~/dev/standardhealth/shr-spec/spec/
```

This completed successfully.  The qa shows all the normal issues we've come to expect in an STU3 ig:
* lots of errors about modeldoc missing header/footer markers and a publish box
* lots of broken links referencing things defined in R4 (but not in R3)
* value sets that don't resolve because they're defined in R4 (not in R3)

@ngfreiter -- if you have the time to look at this again, I'd suggest just confirming using `sw-ig`.

And if you merge this PLEASE USE **SQUASH AND MERGE** -- because I don't want all three IG Publisher jars from this PR getting pushed to the master branch commit log.

**Comment by ngfreiter** [comment]
Woohoo sucess with using `ig-sw`. Looks good to me and works fine for me now, so I will merge.

**Pull request merged**
